"use client";

import { useState } from "react";
import { Sparkles, ImageIcon } from "lucide-react";

type Lang = "de" | "en";

const TX = {
  de: {
    placeholder: "Beschreibe dein Bild... z.B. \"Modernes Büro mit Pflanzen\"",
    btn: "KI-Bild generieren",
    loading: "KI generiert dein Bild...",
    suggestions: ["Modernes Büro mit Pflanzen", "Sonnenuntergang über Mosbach", "Elegantes Restaurant bei Nacht", "Futuristisches Rechenzentrum", "Gemütliches Café mit Holzmöbeln"],
    label: "Generiert von KI",
    disclaimer: "Demo: KI-Bildgenerierung simuliert. In Echtheit powered by DALL·E / Stable Diffusion.",
    tryOne: "Vorschlag:",
  },
  en: {
    placeholder: "Describe your image... e.g. \"Modern office with plants\"",
    btn: "Generate AI image",
    loading: "AI is generating your image...",
    suggestions: ["Modern office with plants", "Sunset over a city", "Elegant restaurant at night", "Futuristic data center", "Cozy café with wooden furniture"],
    label: "Generated by AI",
    disclaimer: "Demo: AI image generation simulated. In production powered by DALL·E / Stable Diffusion.",
    tryOne: "Suggestion:",
  },
};

const ARTWORKS = [
  {
    keywords: ["büro","office","arbeit","work","professional","firma","company","business"],
    gradient: "from-indigo-900 via-slate-800 to-indigo-950",
    overlay: "from-indigo-500/20 to-slate-600/20",
    elements: [
      { style: "absolute top-8 left-8 w-32 h-20 rounded-xl bg-white/10 border border-white/20 backdrop-blur" },
      { style: "absolute top-8 right-8 w-20 h-20 rounded-xl bg-indigo-500/20 border border-indigo-400/30" },
      { style: "absolute bottom-12 left-12 w-full max-w-xs h-2 bg-white/20 rounded-full" },
      { style: "absolute bottom-16 left-12 w-48 h-2 bg-indigo-400/40 rounded-full" },
      { style: "absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-24 h-24 rounded-2xl bg-indigo-600/30 border border-indigo-400/30 backdrop-blur" },
    ],
    label: "🏢 Professionelles Büro",
  },
  {
    keywords: ["restaurant","essen","food","küche","kitchen","café","cafe","gemütlich","cozy"],
    gradient: "from-amber-950 via-orange-950 to-red-950",
    overlay: "from-amber-500/20 to-orange-600/20",
    elements: [
      { style: "absolute inset-0 opacity-30" },
      { style: "absolute bottom-8 left-1/2 -translate-x-1/2 w-48 h-24 rounded-2xl bg-amber-900/60 border border-amber-600/40 backdrop-blur" },
      { style: "absolute top-8 left-8 w-16 h-16 rounded-full bg-amber-500/30 border border-amber-400/40" },
      { style: "absolute top-8 right-8 w-24 h-16 rounded-xl bg-orange-800/40 border border-orange-600/30" },
    ],
    label: "🍽️ Elegantes Restaurant",
  },
  {
    keywords: ["natur","park","pflanz","plant","garden","garten","natur","sunset","sonnenuntergang","city","stadt"],
    gradient: "from-emerald-950 via-teal-900 to-cyan-950",
    overlay: "from-emerald-500/20 to-teal-500/20",
    elements: [
      { style: "absolute bottom-0 left-0 right-0 h-24 bg-gradient-to-t from-emerald-900/60 to-transparent" },
      { style: "absolute top-8 left-1/2 -translate-x-1/2 w-32 h-32 rounded-full bg-teal-400/10 border border-teal-400/20 blur-xl" },
      { style: "absolute bottom-8 left-8 w-12 h-20 rounded-t-full bg-emerald-700/40 border border-emerald-600/30" },
      { style: "absolute bottom-8 right-8 w-8 h-16 rounded-t-full bg-emerald-600/40 border border-emerald-500/30" },
    ],
    label: "🌿 Natur & Landschaft",
  },
  {
    keywords: ["tech","digital","computer","code","futur","rechenzentrum","data","server","ki","ai","robot"],
    gradient: "from-cyan-950 via-blue-950 to-indigo-950",
    overlay: "from-cyan-500/20 to-blue-600/20",
    elements: [
      { style: "absolute top-4 left-4 right-4 h-px bg-cyan-400/30" },
      { style: "absolute top-8 left-4 right-4 h-px bg-cyan-400/20" },
      { style: "absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-32 h-32 rounded-full border border-cyan-400/30 animate-pulse" },
      { style: "absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-20 h-20 rounded-full border border-cyan-400/20" },
      { style: "absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-8 h-8 rounded-full bg-cyan-500/40 border border-cyan-400/60" },
      { style: "absolute bottom-4 left-4 w-24 h-1 bg-cyan-400/40 rounded" },
      { style: "absolute bottom-8 left-4 w-16 h-1 bg-cyan-400/20 rounded" },
    ],
    label: "⚡ Tech & Digital",
  },
  {
    keywords: [],
    gradient: "from-violet-950 via-fuchsia-950 to-purple-950",
    overlay: "from-violet-500/20 to-fuchsia-600/20",
    elements: [
      { style: "absolute top-1/4 left-1/4 w-32 h-32 rounded-full bg-violet-500/20 blur-2xl" },
      { style: "absolute bottom-1/4 right-1/4 w-24 h-24 rounded-full bg-fuchsia-500/20 blur-2xl" },
      { style: "absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-40 h-40 rounded-full border border-violet-400/20 animate-spin" , extra: { animationDuration: "8s" } },
      { style: "absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-24 h-24 rounded-full border border-fuchsia-400/30" },
    ],
    label: "🎨 Abstraktes Kunstwerk",
  },
];

function getArtwork(prompt: string) {
  const lower = prompt.toLowerCase();
  for (const art of ARTWORKS) {
    if (art.keywords.some((k) => lower.includes(k))) return art;
  }
  return ARTWORKS[4];
}

export default function ImageGenDemo({ lang }: { lang: Lang }) {
  const tx = TX[lang];
  const [prompt, setPrompt] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<typeof ARTWORKS[0] | null>(null);

  function generate(p?: string) {
    const text = p ?? prompt;
    if (!text.trim()) return;
    if (p) setPrompt(p);
    setResult(null);
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
      setResult(getArtwork(text));
    }, 2200);
  }

  return (
    <div className="space-y-5">
      {/* Input */}
      <div className="flex gap-3">
        <input
          className="flex-1 bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-white text-sm placeholder:text-zinc-600 outline-none focus:border-indigo-500/50 transition-colors"
          placeholder={tx.placeholder}
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && generate()}
        />
        <button
          onClick={() => generate()}
          disabled={!prompt.trim() || loading}
          className="flex items-center gap-2 px-5 py-3 rounded-xl bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-500 hover:to-violet-500 disabled:opacity-40 text-white text-sm font-semibold transition-all whitespace-nowrap"
        >
          <Sparkles size={15} />
          {tx.btn}
        </button>
      </div>

      {/* Suggestions */}
      <div className="flex flex-wrap gap-2">
        <span className="text-zinc-600 text-xs self-center">{tx.tryOne}</span>
        {tx.suggestions.map((s) => (
          <button
            key={s}
            onClick={() => generate(s)}
            className="text-xs px-3 py-1.5 rounded-full border border-white/10 text-zinc-400 hover:text-white hover:border-indigo-500/40 transition-colors"
          >
            {s}
          </button>
        ))}
      </div>

      {/* Output */}
      <div className="relative rounded-2xl border border-white/10 overflow-hidden" style={{ height: 280 }}>
        {!loading && !result && (
          <div className="h-full flex flex-col items-center justify-center gap-3">
            <ImageIcon size={36} className="text-zinc-700" />
            <p className="text-zinc-600 text-sm">Dein KI-Bild erscheint hier</p>
          </div>
        )}

        {loading && (
          <div className="h-full flex flex-col items-center justify-center gap-4">
            <div className="w-full h-full absolute inset-0 bg-gradient-to-br from-zinc-900 to-zinc-800">
              <div className="absolute inset-0 animate-pulse bg-gradient-to-r from-transparent via-white/5 to-transparent" style={{ backgroundSize: "200% 100%", animation: "shimmer 1.5s infinite" }} />
            </div>
            <div className="relative z-10 flex flex-col items-center gap-3">
              <div className="w-12 h-12 rounded-full border-2 border-indigo-500 border-t-transparent animate-spin" />
              <p className="text-zinc-400 text-sm">{tx.loading}</p>
            </div>
          </div>
        )}

        {result && !loading && (
          <div className={`h-full relative bg-gradient-to-br ${result.gradient}`}>
            <div className={`absolute inset-0 bg-gradient-to-br ${result.overlay}`} />
            {result.elements.map((el, i) => (
              <div key={i} className={el.style} style={(el as any).extra ?? {}} />
            ))}
            <div className="absolute bottom-3 left-3 flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-black/50 border border-white/10 backdrop-blur text-xs text-white">
              <Sparkles size={10} className="text-indigo-300" /> {tx.label} · {result.label}
            </div>
          </div>
        )}
      </div>

      <p className="text-zinc-700 text-xs text-center">{tx.disclaimer}</p>

      <style>{`
        @keyframes shimmer {
          0% { background-position: -200% 0; }
          100% { background-position: 200% 0; }
        }
      `}</style>
    </div>
  );
}
