"use client";

import { useState } from "react";
import { Sparkles, ImageIcon, RefreshCw } from "lucide-react";

type Lang = "de" | "en";

const TX = {
  de: {
    placeholder: 'Beschreibe dein Bild... z.B. "Modernes Büro mit Pflanzen"',
    btn: "KI-Bild generieren",
    loading: "KI generiert dein Bild...",
    suggestions: ["Modernes Büro mit Pflanzen", "Luxuriöses Restaurant bei Nacht", "Futuristisches Rechenzentrum", "Gemütliches Café mit Holzmöbeln", "Professionelles Immobilienbüro"],
    label: "Generiert von KI",
    disclaimer: "Echte KI-Bildgenerierung via Pollinations AI · Kostenlos & ohne API-Key",
    tryOne: "Vorschlag:",
    retry: "Neu generieren",
  },
  en: {
    placeholder: 'Describe your image... e.g. "Modern office with plants"',
    btn: "Generate AI image",
    loading: "AI is generating your image...",
    suggestions: ["Modern office with plants", "Luxury restaurant at night", "Futuristic data center", "Cozy café with wooden furniture", "Professional real estate office"],
    label: "Generated by AI",
    disclaimer: "Real AI image generation via Pollinations AI · Free & no API key required",
    tryOne: "Suggestion:",
    retry: "Regenerate",
  },
};

function buildUrl(prompt: string) {
  const seed = Math.floor(Math.random() * 99999);
  return `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=800&height=450&seed=${seed}&nologo=true&enhance=true`;
}

export default function ImageGenDemo({ lang }: { lang: Lang }) {
  const tx = TX[lang];
  const [prompt, setPrompt] = useState("");
  const [loading, setLoading] = useState(false);
  const [pendingUrl, setPendingUrl] = useState<string | null>(null);
  const [imgUrl, setImgUrl] = useState<string | null>(null);
  const [currentPrompt, setCurrentPrompt] = useState("");

  function generate(p?: string) {
    const text = (p ?? prompt).trim();
    if (!text) return;
    if (p) setPrompt(p);
    setImgUrl(null);
    setLoading(true);
    setCurrentPrompt(text);
    setPendingUrl(buildUrl(text));
  }

  function regenerate() {
    if (!currentPrompt) return;
    setImgUrl(null);
    setLoading(true);
    setPendingUrl(buildUrl(currentPrompt));
  }

  return (
    <div className="space-y-5">
      {/* Input */}
      <div className="flex gap-3">
        <input
          className="flex-1 bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-white text-sm placeholder:text-zinc-600 outline-none focus:border-indigo-500/50 transition-colors"
          placeholder={tx.placeholder}
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && generate()}
        />
        <button
          onClick={() => generate()}
          disabled={!prompt.trim() || loading}
          className="flex items-center gap-2 px-5 py-3 rounded-xl bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-500 hover:to-violet-500 disabled:opacity-40 text-white text-sm font-semibold transition-all whitespace-nowrap"
        >
          <Sparkles size={15} />
          {tx.btn}
        </button>
      </div>

      {/* Suggestions */}
      <div className="flex flex-wrap gap-2 items-center">
        <span className="text-zinc-600 text-xs">{tx.tryOne}</span>
        {tx.suggestions.map((s) => (
          <button
            key={s}
            onClick={() => generate(s)}
            className="text-xs px-3 py-1.5 rounded-full border border-white/10 text-zinc-400 hover:text-white hover:border-indigo-500/40 transition-colors"
          >
            {s}
          </button>
        ))}
      </div>

      {/* Output */}
      <div className="relative rounded-2xl border border-white/10 overflow-hidden bg-zinc-900" style={{ height: 300 }}>
        {/* Empty state */}
        {!loading && !imgUrl && !pendingUrl && (
          <div className="h-full flex flex-col items-center justify-center gap-3">
            <ImageIcon size={36} className="text-zinc-700" />
            <p className="text-zinc-600 text-sm">Dein KI-Bild erscheint hier</p>
          </div>
        )}

        {/* Loading spinner */}
        {loading && (
          <div className="absolute inset-0 flex flex-col items-center justify-center gap-4 bg-zinc-900 z-10">
            <div className="relative">
              <div className="w-14 h-14 rounded-full border-2 border-indigo-500/30 border-t-indigo-500 animate-spin" />
              <div className="absolute inset-0 flex items-center justify-center">
                <Sparkles size={18} className="text-indigo-400" />
              </div>
            </div>
            <p className="text-zinc-400 text-sm">{tx.loading}</p>
            <div className="flex gap-1">
              {[0,1,2].map(i => (
                <div key={i} className="w-1.5 h-1.5 rounded-full bg-indigo-500 animate-bounce" style={{ animationDelay: `${i * 150}ms` }} />
              ))}
            </div>
          </div>
        )}

        {/* Hidden img tag that loads the real image */}
        {pendingUrl && (
          <img
            key={pendingUrl}
            src={pendingUrl}
            alt={currentPrompt}
            className={`w-full h-full object-cover transition-opacity duration-500 ${imgUrl ? "opacity-100" : "opacity-0"}`}
            onLoad={() => { setImgUrl(pendingUrl); setLoading(false); }}
            onError={() => { setLoading(false); setPendingUrl(null); }}
          />
        )}

        {/* Overlay buttons once loaded */}
        {imgUrl && !loading && (
          <div className="absolute bottom-3 left-3 right-3 flex items-center justify-between">
            <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-black/60 border border-white/10 backdrop-blur text-xs text-white">
              <Sparkles size={10} className="text-indigo-300" /> {tx.label}
            </div>
            <button
              onClick={regenerate}
              className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-black/60 border border-white/10 backdrop-blur text-xs text-zinc-300 hover:text-white transition-colors"
            >
              <RefreshCw size={10} /> {tx.retry}
            </button>
          </div>
        )}
      </div>

      <p className="text-zinc-700 text-xs text-center">{tx.disclaimer}</p>
    </div>
  );
}
